/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\paris-bis.glb --shadows --types 
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { RigidBody } from "@react-three/rapier";

type GLTFAction = any;

type GLTFResult = GLTF & {
  nodes: {
    N_Audience_NoMove_01_M_Cmn_AudienceModel_0: THREE.Mesh;
    F_Building_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    F_Building_M_Mobp1_Textures01_0: THREE.Mesh;
    F_Obj_01_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    M_GeneralMansion_Roof_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    M_GeneralMansion_Roof_M_Mobp1_Textures01_0: THREE.Mesh;
    N_MansionObj_01_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    N_MansionObj_01_M_Mobp1_kanban_0: THREE.Mesh;
    N_MansionObj_01_M_Mobp1_Textures01_0: THREE.Mesh;
    N_MansionObj_02_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    N_MansionObj_02_M_Mobp1_kanban_0: THREE.Mesh;
    N_MansionObj_02_M_Mobp1_Textures01_0: THREE.Mesh;
    N_Obj_001_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    N_Obj_001_M_Mobp1_kanban_0: THREE.Mesh;
    N_Obj_002_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    N_Obj_002_M_Mobp1_kanban_0: THREE.Mesh;
    N_Obj_003_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    N_Obj_003_M_Mobp1_kanban_0: THREE.Mesh;
    N_Obj_003_M_Mobp1_Window_0: THREE.Mesh;
    N_Obj_004_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    N_Obj_004_M_Mobp1_kanban_0: THREE.Mesh;
    N_Obj_005_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    N_Obj_005_M_Mobp1_kanban_0: THREE.Mesh;
    N_Obj_005_M_Mobp1_Window_0: THREE.Mesh;
    N_Obj_006_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    N_Obj_006_M_Mobp1_kanban_0: THREE.Mesh;
    N_Obj_007_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    N_Obj_007_M_Mobp1_kanban_0: THREE.Mesh;
    N_Obj_008_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    N_Obj_008_M_Mobp1_kanban_0: THREE.Mesh;
    N_Obj_009_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    N_Obj_009_M_Mobp1_kanban_0: THREE.Mesh;
    N_Obj_010_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    N_Obj_010_M_Mobp1_kanban_0: THREE.Mesh;
    N_UniqueBuilding_Parts_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    N_UniqueBuilding_Parts_M_Mobp1_kanban_0: THREE.Mesh;
    Rainbow_model_M_Mobp1_Rainbow_0: THREE.Mesh;
    F_BlindBuilding_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    F_BlindBuilding_M_Mobp1_Textures01_0: THREE.Mesh;
    F_effel_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    F_Ground_01_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    F_Ground_01_M_Mobp1_Textures01_0: THREE.Mesh;
    F_Ground_01_M_Mobp1_Water_0: THREE.Mesh;
    F_Ground_01_M_Mobp1_Window_0: THREE.Mesh;
    Gmob_Paris_VR_M_Mobp1_VR_0: THREE.Mesh;
    M_Building_001_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    M_Building_001_M_Mobp1_Textures01_0: THREE.Mesh;
    M_Building_001_M_Mobp1_Window_0: THREE.Mesh;
    N_Building_001_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    N_Building_001_M_Mobp1_Textures01_0: THREE.Mesh;
    N_Building_001_M_Mobp1_Window_0: THREE.Mesh;
    N_Building_002_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    N_Building_002_M_Mobp1_gaisenmon_tex_0: THREE.Mesh;
    N_Building_002_M_Mobp1_kanban_0: THREE.Mesh;
    N_Building_002_M_Mobp1_Textures01_0: THREE.Mesh;
    N_Building_002_M_Mobp1_Window_0: THREE.Mesh;
    N_Building_003_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    N_Building_003_M_Mobp1_Textures01_0: THREE.Mesh;
    N_Building_003_M_Mobp1_Window_0: THREE.Mesh;
    N_Building_004_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    N_Building_004_M_Mobp1_Textures01_0: THREE.Mesh;
    N_Building_004_M_Mobp1_Window_0: THREE.Mesh;
    N_effel_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    N_effel_M_Mobp1_Window_0: THREE.Mesh;
    N_Obj_000_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    N_Obj_000_M_Mobp1_Textures01_0: THREE.Mesh;
    N_Obj_000_M_Mobp1_Transparent_0: THREE.Mesh;
    N_Obj_000_M_Mobp1_Window_0: THREE.Mesh;
    N_UniqueBuilding_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    N_UniqueBuilding_M_Mobp1_gaisenmon_tex_0: THREE.Mesh;
    N_UniqueBuilding_M_Mobp1_Textures01_0: THREE.Mesh;
    N_UniqueBuilding_M_Mobp1_Window_0: THREE.Mesh;
    BlindTree_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    Low_Obj_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    Low_Obj_M_Mobp1_kanban_0: THREE.Mesh;
    N_Road_Ground_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    N_Road_Ground_M_Mobp1_Road_A_0: THREE.Mesh;
    N_Road_Ground_M_Mobp1_Road_B_0: THREE.Mesh;
    N_Road_Ground_M_Mobp1_RoadColor_0: THREE.Mesh;
    N_Road_Ground_M_Mobp1_Water_0: THREE.Mesh;
    N_Road_Ground_M_Mobp1_Window_0: THREE.Mesh;
    N_Trocadero_M_Cmn_MainColor_Detail_0: THREE.Mesh;
    N_Trocadero_M_Mobp1_RoadColor_0: THREE.Mesh;
    N_Trocadero_Water_M_Mobp1_Water_0: THREE.Mesh;
    ShadowCollision_M_Cmn_ShadowCollision_0: THREE.Mesh;
  };
  materials: {
    M_Cmn_AudienceModel: THREE.MeshStandardMaterial;
    M_Cmn_MainColor_Detail: THREE.MeshStandardMaterial;
    M_Mobp1_Textures01: THREE.MeshStandardMaterial;
    M_Mobp1_kanban: THREE.MeshStandardMaterial;
    M_Mobp1_Window: THREE.MeshStandardMaterial;
    M_Mobp1_Rainbow: THREE.MeshStandardMaterial;
    M_Mobp1_Water: THREE.MeshStandardMaterial;
    M_Mobp1_VR: THREE.MeshStandardMaterial;
    M_Mobp1_gaisenmon_tex: THREE.MeshStandardMaterial;
    M_Mobp1_Transparent: THREE.MeshStandardMaterial;
    M_Mobp1_Road_A: THREE.MeshStandardMaterial;
    M_Mobp1_Road_B: THREE.MeshStandardMaterial;
    M_Mobp1_RoadColor: THREE.MeshStandardMaterial;
    M_Cmn_ShadowCollision: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function ParisBis(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/tracks/paris-bis.glb"
  ) as GLTFResult;

  const transparentMaterial = new THREE.MeshLambertMaterial({
    transparent: true,
    opacity: 0.01,
  });

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Audience_NoMove_01_M_Cmn_AudienceModel_0.geometry}
          material={materials.M_Cmn_AudienceModel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.F_Building_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.F_Building_M_Mobp1_Textures01_0.geometry}
          material={materials.M_Mobp1_Textures01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.F_Obj_01_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.M_GeneralMansion_Roof_M_Cmn_MainColor_Detail_0.geometry
          }
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.M_GeneralMansion_Roof_M_Mobp1_Textures01_0.geometry}
          material={materials.M_Mobp1_Textures01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_MansionObj_01_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_MansionObj_01_M_Mobp1_kanban_0.geometry}
          material={materials.M_Mobp1_kanban}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_MansionObj_01_M_Mobp1_Textures01_0.geometry}
          material={materials.M_Mobp1_Textures01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_MansionObj_02_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_MansionObj_02_M_Mobp1_kanban_0.geometry}
          material={materials.M_Mobp1_kanban}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_MansionObj_02_M_Mobp1_Textures01_0.geometry}
          material={materials.M_Mobp1_Textures01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Obj_001_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Obj_001_M_Mobp1_kanban_0.geometry}
          material={materials.M_Mobp1_kanban}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Obj_002_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Obj_002_M_Mobp1_kanban_0.geometry}
          material={materials.M_Mobp1_kanban}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Obj_003_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Obj_003_M_Mobp1_kanban_0.geometry}
          material={materials.M_Mobp1_kanban}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Obj_003_M_Mobp1_Window_0.geometry}
          material={materials.M_Mobp1_Window}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Obj_004_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Obj_004_M_Mobp1_kanban_0.geometry}
          material={materials.M_Mobp1_kanban}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Obj_005_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Obj_005_M_Mobp1_kanban_0.geometry}
          material={materials.M_Mobp1_kanban}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Obj_005_M_Mobp1_Window_0.geometry}
          material={materials.M_Mobp1_Window}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Obj_006_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Obj_006_M_Mobp1_kanban_0.geometry}
          material={materials.M_Mobp1_kanban}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Obj_007_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Obj_007_M_Mobp1_kanban_0.geometry}
          material={materials.M_Mobp1_kanban}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Obj_008_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Obj_008_M_Mobp1_kanban_0.geometry}
          material={materials.M_Mobp1_kanban}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Obj_009_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Obj_009_M_Mobp1_kanban_0.geometry}
          material={materials.M_Mobp1_kanban}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Obj_010_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Obj_010_M_Mobp1_kanban_0.geometry}
          material={materials.M_Mobp1_kanban}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.N_UniqueBuilding_Parts_M_Cmn_MainColor_Detail_0.geometry
          }
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_UniqueBuilding_Parts_M_Mobp1_kanban_0.geometry}
          material={materials.M_Mobp1_kanban}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rainbow_model_M_Mobp1_Rainbow_0.geometry}
          material={materials.M_Mobp1_Rainbow}
          position={[-16, 0.14, 0]}
          rotation={[0, -1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.F_BlindBuilding_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.F_BlindBuilding_M_Mobp1_Textures01_0.geometry}
          material={materials.M_Mobp1_Textures01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.F_effel_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.F_Ground_01_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.F_Ground_01_M_Mobp1_Textures01_0.geometry}
          material={materials.M_Mobp1_Textures01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.F_Ground_01_M_Mobp1_Water_0.geometry}
          material={materials.M_Mobp1_Water}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.F_Ground_01_M_Mobp1_Window_0.geometry}
          material={materials.M_Mobp1_Window}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Gmob_Paris_VR_M_Mobp1_VR_0.geometry}
          material={materials.M_Mobp1_VR}
          position={[0, -451.06, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.M_Building_001_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.M_Building_001_M_Mobp1_Textures01_0.geometry}
          material={materials.M_Mobp1_Textures01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.M_Building_001_M_Mobp1_Window_0.geometry}
          material={materials.M_Mobp1_Window}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Building_001_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Building_001_M_Mobp1_Textures01_0.geometry}
          material={materials.M_Mobp1_Textures01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Building_001_M_Mobp1_Window_0.geometry}
          material={materials.M_Mobp1_Window}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Building_002_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Building_002_M_Mobp1_gaisenmon_tex_0.geometry}
          material={materials.M_Mobp1_gaisenmon_tex}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Building_002_M_Mobp1_kanban_0.geometry}
          material={materials.M_Mobp1_kanban}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Building_002_M_Mobp1_Textures01_0.geometry}
          material={materials.M_Mobp1_Textures01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Building_002_M_Mobp1_Window_0.geometry}
          material={materials.M_Mobp1_Window}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Building_003_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Building_003_M_Mobp1_Textures01_0.geometry}
          material={materials.M_Mobp1_Textures01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Building_003_M_Mobp1_Window_0.geometry}
          material={materials.M_Mobp1_Window}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Building_004_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Building_004_M_Mobp1_Textures01_0.geometry}
          material={materials.M_Mobp1_Textures01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Building_004_M_Mobp1_Window_0.geometry}
          material={materials.M_Mobp1_Window}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_effel_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_effel_M_Mobp1_Window_0.geometry}
          material={materials.M_Mobp1_Window}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Obj_000_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Obj_000_M_Mobp1_Textures01_0.geometry}
          material={materials.M_Mobp1_Textures01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Obj_000_M_Mobp1_Transparent_0.geometry}
          material={materials.M_Mobp1_Transparent}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Obj_000_M_Mobp1_Window_0.geometry}
          material={materials.M_Mobp1_Window}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_UniqueBuilding_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_UniqueBuilding_M_Mobp1_gaisenmon_tex_0.geometry}
          material={materials.M_Mobp1_gaisenmon_tex}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_UniqueBuilding_M_Mobp1_Textures01_0.geometry}
          material={materials.M_Mobp1_Textures01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_UniqueBuilding_M_Mobp1_Window_0.geometry}
          material={materials.M_Mobp1_Window}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BlindTree_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Low_Obj_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Low_Obj_M_Mobp1_kanban_0.geometry}
          material={materials.M_Mobp1_kanban}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Road_Ground_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Road_Ground_M_Mobp1_Road_A_0.geometry}
          material={materials.M_Mobp1_Road_A}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Road_Ground_M_Mobp1_Road_B_0.geometry}
          material={materials.M_Mobp1_Road_B}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Road_Ground_M_Mobp1_RoadColor_0.geometry}
          material={materials.M_Mobp1_RoadColor}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Road_Ground_M_Mobp1_Water_0.geometry}
          material={materials.M_Mobp1_Water}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Road_Ground_M_Mobp1_Window_0.geometry}
          material={materials.M_Mobp1_Window}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Trocadero_M_Cmn_MainColor_Detail_0.geometry}
          material={materials.M_Cmn_MainColor_Detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Trocadero_M_Mobp1_RoadColor_0.geometry}
          material={materials.M_Mobp1_RoadColor}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.N_Trocadero_Water_M_Mobp1_Water_0.geometry}
          material={materials.M_Mobp1_Water}
        />
        <RigidBody type="fixed" colliders="trimesh" name="terrain">
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ShadowCollision_M_Cmn_ShadowCollision_0.geometry}
            material={transparentMaterial}
            position={[0, 0.244, 0]}
          />
        </RigidBody>
      </group>
    </group>
  );
}

useGLTF.preload("/models/tracks/paris-bis.glb");
